import type { Database } from "./types";
import { format, addDays, subDays } from "date-fns";

const d = (offset: number) => format(addDays(new Date(), offset), "yyyy-MM-dd");
const dt = (offset: number) =>
  new Date(addDays(new Date(), offset).setHours(10, 30, 0, 0)).toISOString();
const past = (offset: number) => format(subDays(new Date(), offset), "yyyy-MM-dd");

export function buildSeed(): Database {
  const agencies = [
    {
      id: "ag_clb_ca",
      name: "California Contractors State License Board",
      agencyType: "Contractor Licensing Board" as const,
      stateRegion: "California",
      departmentCategory: "Construction Licensing",
      website: "https://www.cslb.ca.gov",
      portalLink: "https://www.cslb.ca.gov/onlineservices",
      loginAccessNotes: "Shared department login. MFA code sent to compliance@company.com.",
      mainPhone: "(800) 321-2752",
      mainEmail: "info@cslb.ca.gov",
      contactPerson: "Licensing Unit",
      preferredCommunicationMethod: "Portal Message" as const,
      followUpTimingRules: "Allow 15 business days before status follow-up.",
      knownProcessingPatterns: "Application review averages 4-6 weeks; faster mid-quarter.",
      commonIssues: "Bond verification mismatches, expired workers' comp certificates.",
      escalationNotes: "Escalate to Licensing Supervisor only after two unanswered portal messages.",
      activeStatus: "Active" as const,
      createdAt: dt(-120),
    },
    {
      id: "ag_dor_tx",
      name: "Texas Comptroller of Public Accounts",
      agencyType: "Department of Revenue" as const,
      stateRegion: "Texas",
      departmentCategory: "Tax & Revenue",
      website: "https://comptroller.texas.gov",
      portalLink: "https://mycpa.cpa.state.tx.us",
      loginAccessNotes: "WebFile number stored in password manager under 'TX Comptroller'.",
      mainPhone: "(800) 252-5555",
      mainEmail: "tax.help@cpa.texas.gov",
      contactPerson: "Sales Tax Division",
      preferredCommunicationMethod: "Phone" as const,
      followUpTimingRules: "Call between 8-10am CT for shortest hold times.",
      knownProcessingPatterns: "Refund and permit reviews run 3-5 weeks.",
      commonIssues: "NAICS code mismatches; nexus questionnaires.",
      escalationNotes: "Request a supervisor reference number on every call.",
      activeStatus: "Active" as const,
      createdAt: dt(-110),
    },
    {
      id: "ag_dot_fl",
      name: "Florida Department of Transportation",
      agencyType: "Department of Transportation" as const,
      stateRegion: "Florida",
      departmentCategory: "Transportation Permitting",
      website: "https://www.fdot.gov",
      portalLink: "https://gis.fdot.gov/permits",
      loginAccessNotes: "Per-user accounts required. Emily and account managers have individual logins.",
      mainPhone: "(850) 414-4100",
      mainEmail: "permits@dot.state.fl.us",
      contactPerson: "District 5 Permits Office",
      preferredCommunicationMethod: "Email" as const,
      followUpTimingRules: "Follow up weekly on open oversize/overweight permits.",
      knownProcessingPatterns: "Routine permits same-day; special hauling 5-10 days.",
      commonIssues: "Route surveys missing; insurance certificate gaps.",
      escalationNotes: "District permit manager handles stalled special permits.",
      activeStatus: "Active" as const,
      createdAt: dt(-95),
    },
    {
      id: "ag_epa_reg5",
      name: "US EPA Region 5",
      agencyType: "Environmental Agency / EPA" as const,
      stateRegion: "Midwest (Region 5)",
      departmentCategory: "Environmental Compliance",
      website: "https://www.epa.gov/aboutepa/epa-region-5",
      portalLink: "https://cdx.epa.gov",
      loginAccessNotes: "CDX account tied to facility ID. Re-verify every 90 days.",
      mainPhone: "(312) 353-2000",
      mainEmail: "r5.info@epa.gov",
      contactPerson: "Air Permits Branch",
      preferredCommunicationMethod: "Portal Message" as const,
      followUpTimingRules: "Allow 30 days; reporting deadlines are strict.",
      knownProcessingPatterns: "Title V actions are slow; expect multi-month timelines.",
      commonIssues: "Emissions inventory format errors; missing signatures.",
      escalationNotes: "Document all submissions; escalate via formal letter.",
      activeStatus: "Active" as const,
      createdAt: dt(-80),
    },
    {
      id: "ag_sos_de",
      name: "Delaware Secretary of State",
      agencyType: "Secretary of State" as const,
      stateRegion: "Delaware",
      departmentCategory: "Corporate Registration",
      website: "https://sos.delaware.gov",
      portalLink: "https://icis.corp.delaware.gov",
      loginAccessNotes: "Registered agent handles most filings; portal read-only for us.",
      mainPhone: "(302) 739-3073",
      mainEmail: "dosdoc_ftax@delaware.gov",
      contactPerson: "Division of Corporations",
      preferredCommunicationMethod: "Email" as const,
      followUpTimingRules: "Annual report due March 1; confirm filing by Feb 15.",
      knownProcessingPatterns: "Standard filings 1-2 weeks; expedited available.",
      commonIssues: "Franchise tax calculation disputes.",
      escalationNotes: "Use registered agent escalation channel first.",
      activeStatus: "Active" as const,
      createdAt: dt(-70),
    },
    {
      id: "ag_perm_phx",
      name: "City of Phoenix Permitting Office",
      agencyType: "Local Permitting Office" as const,
      stateRegion: "Arizona",
      departmentCategory: "Local Permits",
      website: "https://www.phoenix.gov/pdd",
      portalLink: "https://eservices.phoenix.gov/PlanningDevelopment",
      loginAccessNotes: "SHAPE PHX portal account under project email.",
      mainPhone: "(602) 262-7811",
      mainEmail: "pdd.info@phoenix.gov",
      contactPerson: "Commercial Plan Review",
      preferredCommunicationMethod: "Portal Message" as const,
      followUpTimingRules: "Check portal twice weekly during active review.",
      knownProcessingPatterns: "First review 15 business days; resubmittals faster.",
      commonIssues: "Incomplete plan sets; fee holds.",
      escalationNotes: "Plan review supervisor for stalled commercial reviews.",
      activeStatus: "Inactive" as const,
      createdAt: dt(-60),
    },
  ];

  const matters = [
    {
      id: "mt_001",
      title: "General Contractor License Renewal",
      clientOrCompanyName: "Summit Builders LLC",
      agencyId: "ag_clb_ca",
      matterType: "License Renewal" as const,
      stateJurisdiction: "California",
      currentStatus: "Waiting on Agency" as const,
      priorityRiskLevel: "High" as const,
      internalOwner: "Marcus Lee",
      emilyOwnerStatus: "Actively tracking",
      dateOpened: past(28),
      lastContactDate: past(9),
      nextFollowUpDate: d(2),
      deadlineRenewalDate: d(18),
      submissionDate: past(12),
      waitingOn: "Agency",
      nextAction: "Send portal status follow-up after 15-day window.",
      notes: "Bond verification was flagged once; re-submitted corrected certificate.",
      referenceLinks: "https://www.cslb.ca.gov/onlineservices",
      createdAt: dt(-28),
    },
    {
      id: "mt_002",
      title: "Sales Tax Permit Nexus Review",
      clientOrCompanyName: "Brightline Retail Co.",
      agencyId: "ag_dor_tx",
      matterType: "Tax / Revenue" as const,
      stateJurisdiction: "Texas",
      currentStatus: "Deficiency Received" as const,
      priorityRiskLevel: "Critical" as const,
      internalOwner: "Emily Jones",
      emilyOwnerStatus: "Personally handling",
      dateOpened: past(40),
      lastContactDate: past(3),
      nextFollowUpDate: d(1),
      deadlineRenewalDate: d(6),
      submissionDate: past(20),
      waitingOn: "Client",
      nextAction: "Collect NAICS reclassification documents from client.",
      notes: "Comptroller questioned reported business activity codes.",
      referenceLinks: "https://mycpa.cpa.state.tx.us",
      createdAt: dt(-40),
    },
    {
      id: "mt_003",
      title: "Oversize Load Hauling Permit",
      clientOrCompanyName: "Gulfstream Logistics",
      agencyId: "ag_dot_fl",
      matterType: "DOT" as const,
      stateJurisdiction: "Florida",
      currentStatus: "Submitted" as const,
      priorityRiskLevel: "Medium" as const,
      internalOwner: "Dana Ortiz",
      emilyOwnerStatus: "Monitoring",
      dateOpened: past(10),
      lastContactDate: past(4),
      nextFollowUpDate: d(3),
      deadlineRenewalDate: d(9),
      submissionDate: past(5),
      waitingOn: "Agency",
      nextAction: "Confirm route survey accepted by District 5.",
      notes: "Special hauling permit; route survey attached.",
      referenceLinks: "https://gis.fdot.gov/permits",
      createdAt: dt(-10),
    },
    {
      id: "mt_004",
      title: "Title V Air Permit Annual Report",
      clientOrCompanyName: "Ironworks Manufacturing",
      agencyId: "ag_epa_reg5",
      matterType: "Environmental / EPA" as const,
      stateJurisdiction: "Illinois",
      currentStatus: "Escalated" as const,
      priorityRiskLevel: "Critical" as const,
      internalOwner: "Emily Jones",
      emilyOwnerStatus: "Escalated for review",
      dateOpened: past(55),
      lastContactDate: past(14),
      nextFollowUpDate: past(2),
      deadlineRenewalDate: d(4),
      submissionDate: "",
      waitingOn: "Internal Team",
      nextAction: "Confirm emissions inventory format with environmental engineer.",
      notes: "Strict reporting deadline; format errors caused prior rejection.",
      referenceLinks: "https://cdx.epa.gov",
      createdAt: dt(-55),
    },
    {
      id: "mt_005",
      title: "Annual Report & Franchise Tax Filing",
      clientOrCompanyName: "Northstar Holdings Inc.",
      agencyId: "ag_sos_de",
      matterType: "Secretary of State" as const,
      stateJurisdiction: "Delaware",
      currentStatus: "Preparing" as const,
      priorityRiskLevel: "Medium" as const,
      internalOwner: "Priya Nair",
      emilyOwnerStatus: "Monitoring",
      dateOpened: past(18),
      lastContactDate: past(6),
      nextFollowUpDate: d(5),
      deadlineRenewalDate: d(21),
      submissionDate: "",
      waitingOn: "Internal Team",
      nextAction: "Verify franchise tax calculation method before filing.",
      notes: "Registered agent will file once figures confirmed.",
      referenceLinks: "https://icis.corp.delaware.gov",
      createdAt: dt(-18),
    },
    {
      id: "mt_006",
      title: "Commercial Tenant Improvement Permit",
      clientOrCompanyName: "Desert Vista Properties",
      agencyId: "ag_perm_phx",
      matterType: "Permit" as const,
      stateJurisdiction: "Arizona",
      currentStatus: "On Hold" as const,
      priorityRiskLevel: "Low" as const,
      internalOwner: "Dana Ortiz",
      emilyOwnerStatus: "Paused per client",
      dateOpened: past(35),
      lastContactDate: past(22),
      nextFollowUpDate: d(14),
      deadlineRenewalDate: "",
      submissionDate: past(30),
      waitingOn: "Client",
      nextAction: "Await client decision on revised scope before resubmitting.",
      notes: "Fee hold on portal; client reconsidering scope.",
      referenceLinks: "",
      createdAt: dt(-35),
    },
    {
      id: "mt_007",
      title: "New Contractor License Application",
      clientOrCompanyName: "Pinecrest Electrical",
      agencyId: "ag_clb_ca",
      matterType: "License Application" as const,
      stateJurisdiction: "California",
      currentStatus: "Waiting on Client" as const,
      priorityRiskLevel: "High" as const,
      internalOwner: "Marcus Lee",
      emilyOwnerStatus: "Actively tracking",
      dateOpened: past(15),
      lastContactDate: past(2),
      nextFollowUpDate: d(0),
      deadlineRenewalDate: d(30),
      submissionDate: "",
      waitingOn: "Client",
      nextAction: "Client to provide workers' comp certificate.",
      notes: "Cannot submit until comp certificate received.",
      referenceLinks: "",
      createdAt: dt(-15),
    },
    {
      id: "mt_008",
      title: "Business Registration Renewal",
      clientOrCompanyName: "Brightline Retail Co.",
      agencyId: "ag_sos_de",
      matterType: "Registration" as const,
      stateJurisdiction: "Delaware",
      currentStatus: "Approved / Completed" as const,
      priorityRiskLevel: "Low" as const,
      internalOwner: "Emily Jones",
      emilyOwnerStatus: "Closed out",
      dateOpened: past(70),
      lastContactDate: past(33),
      nextFollowUpDate: "",
      deadlineRenewalDate: past(30),
      submissionDate: past(45),
      waitingOn: "",
      nextAction: "None — confirmation filed to records.",
      notes: "Completed and confirmed via registered agent.",
      referenceLinks: "",
      createdAt: dt(-70),
    },
  ];

  const communications = [
    {
      id: "cm_001",
      dateTime: dt(-9),
      agencyId: "ag_clb_ca",
      matterId: "mt_001",
      contactMethod: "Portal Message" as const,
      personContacted: "Licensing Unit",
      summary: "Asked for status of renewal application after resubmitting bond certificate.",
      outcome: "Auto-acknowledgment received; no reviewer assigned yet.",
      nextStep: "Follow up after the 15 business day window.",
      followUpNeeded: true,
      followUpDate: d(2),
      loggedBy: "Marcus Lee",
      attachmentsOrLinks: "Portal confirmation #CSLB-44821",
      createdAt: dt(-9),
    },
    {
      id: "cm_002",
      dateTime: dt(-3),
      agencyId: "ag_dor_tx",
      matterId: "mt_002",
      contactMethod: "Phone" as const,
      personContacted: "Sales Tax Division agent",
      summary: "Discussed NAICS code deficiency and required reclassification documents.",
      outcome: "Agent provided list of acceptable supporting documents.",
      nextStep: "Request documents from client and prepare response.",
      followUpNeeded: true,
      followUpDate: d(1),
      loggedBy: "Emily Jones",
      attachmentsOrLinks: "Call ref #TX-99213",
      createdAt: dt(-3),
    },
    {
      id: "cm_003",
      dateTime: dt(-4),
      agencyId: "ag_dot_fl",
      matterId: "mt_003",
      contactMethod: "Email" as const,
      personContacted: "District 5 Permits Office",
      summary: "Submitted route survey and insurance certificate for special hauling permit.",
      outcome: "Confirmed receipt; review in queue.",
      nextStep: "Check status in 3 days.",
      followUpNeeded: true,
      followUpDate: d(3),
      loggedBy: "Dana Ortiz",
      attachmentsOrLinks: "route-survey-final.pdf",
      createdAt: dt(-4),
    },
    {
      id: "cm_004",
      dateTime: dt(-14),
      agencyId: "ag_epa_reg5",
      matterId: "mt_004",
      contactMethod: "Portal Message" as const,
      personContacted: "Air Permits Branch",
      summary: "Inquired about acceptable emissions inventory format after prior rejection.",
      outcome: "No response yet; matter escalated internally.",
      nextStep: "Escalate via formal letter if no reply.",
      followUpNeeded: true,
      followUpDate: past(2),
      loggedBy: "Emily Jones",
      attachmentsOrLinks: "CDX submission log",
      createdAt: dt(-14),
    },
    {
      id: "cm_005",
      dateTime: dt(-33),
      agencyId: "ag_sos_de",
      matterId: "mt_008",
      contactMethod: "Email" as const,
      personContacted: "Registered Agent",
      summary: "Confirmed business registration renewal was filed and accepted.",
      outcome: "Filing confirmed; matter closed.",
      nextStep: "None.",
      followUpNeeded: false,
      followUpDate: "",
      loggedBy: "Priya Nair",
      attachmentsOrLinks: "DE filing confirmation",
      createdAt: dt(-33),
    },
  ];

  const deficiencies = [
    {
      id: "df_001",
      matterId: "mt_002",
      agencyId: "ag_dor_tx",
      requestOrDeficiencyType: "Missing documentation",
      description: "NAICS code does not match reported business activity; reclassification documents required.",
      dateReceived: past(3),
      dueDate: d(6),
      assignedInternalOwner: "Emily Jones",
      status: "Waiting on Client" as const,
      requiredResponse: "Submit corrected NAICS classification with supporting docs.",
      documentsNeeded: "Business activity statement, prior year returns.",
      riskLevel: "Critical" as const,
      resolutionNotes: "",
      createdAt: dt(-3),
    },
    {
      id: "df_002",
      matterId: "mt_001",
      agencyId: "ag_clb_ca",
      requestOrDeficiencyType: "Correction needed",
      description: "Bond verification certificate did not match licensee name exactly.",
      dateReceived: past(20),
      dueDate: past(6),
      assignedInternalOwner: "Marcus Lee",
      status: "Submitted to Agency" as const,
      requiredResponse: "Provide corrected surety bond certificate.",
      documentsNeeded: "Updated bond certificate.",
      riskLevel: "High" as const,
      resolutionNotes: "Corrected certificate uploaded; awaiting agency confirmation.",
      createdAt: dt(-20),
    },
    {
      id: "df_003",
      matterId: "mt_004",
      agencyId: "ag_epa_reg5",
      requestOrDeficiencyType: "Format error",
      description: "Emissions inventory spreadsheet rejected due to incorrect template version.",
      dateReceived: past(16),
      dueDate: d(4),
      assignedInternalOwner: "Emily Jones",
      status: "Escalated" as const,
      requiredResponse: "Resubmit using current EPA template with signatures.",
      documentsNeeded: "Updated emissions inventory, signed certification.",
      riskLevel: "Critical" as const,
      resolutionNotes: "",
      createdAt: dt(-16),
    },
    {
      id: "df_004",
      matterId: "mt_006",
      agencyId: "ag_perm_phx",
      requestOrDeficiencyType: "Fee hold",
      description: "Plan review on hold pending outstanding review fee payment.",
      dateReceived: past(25),
      dueDate: "",
      assignedInternalOwner: "Dana Ortiz",
      status: "Waiting on Client" as const,
      requiredResponse: "Client to authorize fee payment.",
      documentsNeeded: "Payment authorization.",
      riskLevel: "Low" as const,
      resolutionNotes: "",
      createdAt: dt(-25),
    },
  ];

  const escalations = [
    {
      id: "es_001",
      matterId: "mt_004",
      reasonForEscalation: "Deadline risk" as const,
      summary: "Title V annual report at risk of missing strict EPA deadline due to format rejection.",
      recommendedNextStep: "Confirm correct template with environmental engineer and submit within 4 days.",
      assignedReviewer: "Rose Taylor (Leadership)",
      dateEscalated: past(5),
      dueDate: d(4),
      status: "In Review" as const,
      resolutionNotes: "",
      createdAt: dt(-5),
    },
    {
      id: "es_002",
      matterId: "mt_002",
      reasonForEscalation: "Tax review needed" as const,
      summary: "NAICS reclassification may have tax exposure implications for the client.",
      recommendedNextStep: "Route to tax advisor for interpretation before responding to agency.",
      assignedReviewer: "Tax Advisory Team",
      dateEscalated: past(2),
      dueDate: d(3),
      status: "Awaiting Decision" as const,
      resolutionNotes: "",
      createdAt: dt(-2),
    },
  ];

  const knowledge = [
    {
      id: "kn_001",
      agencyId: "ag_clb_ca",
      stateJurisdiction: "California",
      topic: "Contractor License Renewal Process",
      summary: "How CSLB renewals flow and where they typically stall.",
      detailedNotes: "Renewals are processed in the order received. Bond and workers' comp verification are the most common holdups.",
      portalInstructions: "Log into Online Services, select the license, choose Renew, and upload supporting docs.",
      followUpTimingGuidance: "Wait 15 business days before a status follow-up via portal message.",
      commonDeficiencies: "Bond name mismatch, expired workers' comp certificate.",
      requiredFormsOrLinks: "Renewal application, surety bond certificate.",
      contactPreferences: "Portal message preferred over phone for documentation trail.",
      internalTips: "Always confirm exact licensee legal name on the bond before submitting.",
      lastVerifiedDate: past(20),
      verifiedBy: "Marcus Lee",
      createdAt: dt(-50),
    },
    {
      id: "kn_002",
      agencyId: "ag_dor_tx",
      stateJurisdiction: "Texas",
      topic: "Sales Tax Nexus Questionnaires",
      summary: "Handling Comptroller nexus and NAICS reclassification requests.",
      detailedNotes: "The Comptroller frequently questions NAICS codes that don't align with reported activity. Provide clear supporting documentation.",
      portalInstructions: "Use WebFile to respond; attach documents under the correspondence section.",
      followUpTimingGuidance: "Call 8-10am CT; always capture a reference number.",
      commonDeficiencies: "NAICS mismatches, missing prior-year returns.",
      requiredFormsOrLinks: "Business activity statement, prior returns.",
      contactPreferences: "Phone for fast clarification, portal for formal responses.",
      internalTips: "Document every agent name and call reference number.",
      lastVerifiedDate: past(10),
      verifiedBy: "Emily Jones",
      createdAt: dt(-45),
    },
    {
      id: "kn_003",
      agencyId: "ag_epa_reg5",
      stateJurisdiction: "Midwest (Region 5)",
      topic: "Title V Emissions Inventory Submissions",
      summary: "Avoiding format rejections on annual emissions reports.",
      detailedNotes: "EPA updates the inventory template periodically. Using an outdated template is the leading rejection cause.",
      portalInstructions: "Submit through CDX; verify the template version before upload.",
      followUpTimingGuidance: "Allow 30 days but never miss the reporting deadline.",
      commonDeficiencies: "Outdated template, missing signed certification.",
      requiredFormsOrLinks: "Current emissions inventory template, certification form.",
      contactPreferences: "Portal message with formal letter escalation if unanswered.",
      internalTips: "Download the template fresh from CDX each reporting cycle.",
      lastVerifiedDate: past(35),
      verifiedBy: "Emily Jones",
      createdAt: dt(-40),
    },
  ];

  const sops = [
    {
      id: "sop_001",
      title: "Standard Agency Communication Workflow",
      category: "Agency Communication SOP" as const,
      purpose: "Ensure consistent, documented communication with all agencies.",
      steps: "1. Identify preferred contact method.\n2. Log every contact in the Communication Log.\n3. Capture reference numbers.\n4. Set a follow-up date.\n5. Update the related matter status.",
      owner: "Emily Jones",
      lastUpdated: past(12),
      status: "Active" as const,
      notes: "All external communication must remain human-reviewed.",
      createdAt: dt(-60),
    },
    {
      id: "sop_002",
      title: "Document Naming & Storage Standards",
      category: "Documentation Standards" as const,
      purpose: "Keep documentation consistent and retrievable.",
      steps: "1. Use client-agency-matter naming.\n2. Store final versions only.\n3. Link references in the matter record.",
      owner: "Priya Nair",
      lastUpdated: past(30),
      status: "Active" as const,
      notes: "",
      createdAt: dt(-58),
    },
    {
      id: "sop_003",
      title: "Deficiency Routing Procedure",
      category: "Deficiency Routing SOP" as const,
      purpose: "Route agency deficiencies to the right owner quickly.",
      steps: "1. Log deficiency on receipt.\n2. Assign internal owner.\n3. Set due date earlier than agency deadline.\n4. Track to resolution.",
      owner: "Emily Jones",
      lastUpdated: past(8),
      status: "Active" as const,
      notes: "",
      createdAt: dt(-55),
    },
    {
      id: "sop_004",
      title: "Escalation Decision Rules",
      category: "Escalation Rules" as const,
      purpose: "Define when and how to escalate matters.",
      steps: "1. Identify escalation reason.\n2. Summarize and recommend a next step.\n3. Assign a reviewer.\n4. Track to decision.",
      owner: "Emily Jones",
      lastUpdated: past(15),
      status: "Active" as const,
      notes: "Emily routes; she does not make legal, tax, or pricing decisions.",
      createdAt: dt(-52),
    },
    {
      id: "sop_005",
      title: "Weekly Portal Check Procedure",
      category: "Portal Check Procedure" as const,
      purpose: "Catch agency updates that aren't emailed.",
      steps: "1. Review active matters by agency.\n2. Log into each portal.\n3. Record any status change as a communication.",
      owner: "Dana Ortiz",
      lastUpdated: past(20),
      status: "Active" as const,
      notes: "",
      createdAt: dt(-50),
    },
    {
      id: "sop_006",
      title: "Approved Status Language Guide",
      category: "Approved Status Language" as const,
      purpose: "Keep client-facing status updates accurate and non-committal.",
      steps: "1. Use approved phrasing.\n2. Avoid guaranteeing outcomes.\n3. Note that updates are informational only.",
      owner: "Emily Jones",
      lastUpdated: past(40),
      status: "Under Review" as const,
      notes: "Never guarantee agency outcomes or timelines.",
      createdAt: dt(-48),
    },
    {
      id: "sop_007",
      title: "New Team Member Onboarding",
      category: "New Team Member Training" as const,
      purpose: "Ramp new department members on tools and process.",
      steps: "1. Review all SOPs.\n2. Shadow communications for one week.\n3. Practice logging matters.",
      owner: "Emily Jones",
      lastUpdated: past(60),
      status: "Draft" as const,
      notes: "",
      createdAt: dt(-46),
    },
    {
      id: "sop_008",
      title: "Pre-Submission Quality Review Checklist",
      category: "Quality Review Checklist" as const,
      purpose: "Reduce deficiencies through a final review.",
      steps: "1. Confirm all forms complete.\n2. Verify names match exactly.\n3. Confirm template versions.\n4. Confirm signatures.",
      owner: "Priya Nair",
      lastUpdated: past(5),
      status: "Active" as const,
      notes: "",
      createdAt: dt(-44),
    },
  ];

  const tasks = [
    {
      id: "tk_001",
      title: "Review NAICS reclassification for Brightline",
      priority: "High" as const,
      dueDate: d(1),
      status: "Open" as const,
      assignedTo: "Emily Jones",
      relatedAgencyId: "ag_dor_tx",
      createdAt: dt(-1),
    },
    {
      id: "tk_002",
      title: "Approve route survey submission",
      priority: "Medium" as const,
      dueDate: d(3),
      status: "In Progress" as const,
      assignedTo: "Dana Ortiz",
      relatedAgencyId: "ag_dot_fl",
      createdAt: dt(-2),
    },
    {
      id: "tk_003",
      title: "Upload corrected surety bond",
      priority: "High" as const,
      dueDate: d(0),
      status: "Completed" as const,
      assignedTo: "Emily Jones",
      relatedAgencyId: "ag_clb_ca",
      createdAt: dt(-4),
    },
    {
      id: "tk_004",
      title: "Prepare franchise tax calculation",
      priority: "Medium" as const,
      dueDate: d(5),
      status: "Open" as const,
      assignedTo: "Priya Nair",
      relatedAgencyId: "ag_sos_de",
      createdAt: dt(-1),
    },
    {
      id: "tk_005",
      title: "Verify emissions inventory format",
      priority: "High" as const,
      dueDate: d(2),
      status: "Blocked" as const,
      assignedTo: "Emily Jones",
      relatedAgencyId: "ag_epa_reg5",
      createdAt: dt(-3),
    },
    {
      id: "tk_006",
      title: "Check permit status on portal",
      priority: "Low" as const,
      dueDate: d(4),
      status: "Open" as const,
      assignedTo: "Dana Ortiz",
      relatedAgencyId: "ag_perm_phx",
      createdAt: dt(-1),
    },
  ];

  const alerts = [
    {
      id: "al_001",
      title: "EPA Title V Deadline Approaching",
      detail: "Emissions inventory must be submitted within 4 days to avoid penalties.",
      severity: "Critical" as const,
      type: "Deadline" as const,
      date: d(4),
      createdAt: dt(-1),
    },
    {
      id: "al_002",
      title: "CSLB Bond Format Update",
      detail: "California Contractors State License Board issued a new bond certificate format effective next month.",
      severity: "Warning" as const,
      type: "Update" as const,
      date: d(14),
      createdAt: dt(-2),
    },
    {
      id: "al_003",
      title: "New Local Permitting Guidelines",
      detail: "City of Phoenix updated commercial plan review fee structures.",
      severity: "Info" as const,
      type: "New" as const,
      date: past(1),
      createdAt: dt(-1),
    },
    {
      id: "al_004",
      title: "Overdue: Brightline NAICS Response",
      detail: "Awaiting client documentation for 3 days past target internal SLA.",
      severity: "Warning" as const,
      type: "Overdue" as const,
      date: past(3),
      createdAt: dt(-3),
    },
    {
      id: "al_005",
      title: "Delaware Portal Maintenance",
      detail: "ICIS portal will be offline for maintenance this weekend.",
      severity: "Info" as const,
      type: "Update" as const,
      date: d(2),
      createdAt: dt(-1),
    },
    {
      id: "al_006",
      title: "TX Comptroller Audit Notice",
      detail: "General notice regarding increased scrutiny on retail NAICS codes.",
      severity: "Info" as const,
      type: "New" as const,
      date: past(5),
      createdAt: dt(-5),
    },
  ];

  const bonusOpportunities = [
    {
      id: "bo_library",
      name: "Board Knowledge Library Buildout Bonus",
      amount: "$500 – $1,500 / project",
      criteria:
        "Earned per completed buildout project — documenting agency knowledge, portal instructions, and reusable SOPs into the institutional library.",
      status: "Data-derived",
      tone: "blue" as const,
      meta: "Projected live from logged contributions.",
      dataDerived: true,
      createdAt: dt(-50),
    },
    {
      id: "bo_stipend",
      name: "Board Communications Lead Stipend",
      amount: "$250 – $750 / month",
      criteria:
        "Monthly stipend for leading board and agency communications — coordinating outreach, follow-ups, and routing across regulatory matters.",
      status: "Monthly",
      tone: "purple" as const,
      meta: "Paid monthly while serving as communications lead.",
      createdAt: dt(-49),
    },
    {
      id: "bo_teamlead",
      name: "Team Lead Override / Bonus",
      amount: "Project-based or monthly",
      criteria:
        "Awarded for leading team members on projects or licensing operations — structured as a per-project override or a recurring monthly amount.",
      status: "Variable",
      tone: "amber" as const,
      meta: "Triggered when leading a team on a project or operation.",
      createdAt: dt(-48),
    },
    {
      id: "bo_equity",
      name: "Performance-Based Profit / Equity Consideration",
      amount: "1% – 3% (future)",
      criteria:
        "Future consideration for sustained performance — subject to a separate written agreement. Not currently active.",
      status: "Future",
      tone: "green" as const,
      meta: "Requires a separate written agreement.",
      createdAt: dt(-47),
    },
    {
      id: "bo_path",
      name: "Licensing Operations Manager Path",
      amount: "Reviewed separately",
      criteria:
        "Advancement path into licensing operations management — compensation reviewed separately as the role expands.",
      status: "Path",
      tone: "slate" as const,
      meta: "Compensation reviewed separately upon advancement.",
      createdAt: dt(-46),
    },
  ];

  const compensation = [
    {
      id: "comp_main",
      baseRate: "$30.00 / hr",
      schedule: "35–40 hrs / week",
      createdAt: dt(-120),
    },
  ];

  const reviewTargets = [
    {
      id: "rt_090",
      label: "90-Day Review Target",
      value: "$32–34 / hr",
      targetDate: d(18),
      detail: "Performance-based increase at first review milestone.",
      createdAt: dt(-120),
    },
    {
      id: "rt_180",
      label: "180-Day Review Target",
      value: "$35+ / hr",
      targetDate: d(108),
      detail: "Performance-based increase at second review milestone.",
      createdAt: dt(-119),
    },
  ];

  const employeeProfile = [
    {
      id: "emp_main",
      name: "Emily Jones",
      title: "Director of Compliance & Regulatory Communications",
      department: "Compliance & Regulatory Affairs",
      employeeId: "CCA-0001",
      email: "emily.jones@cca.com",
      phone: "(555) 010-1001",
      location: "Chicago, IL — HQ",
      manager: "Rose Taylor — VP of Operations",
      startDate: "2021-03-03",
      employmentType: "Full-time · Hourly (Non-Exempt)",
      emergencyContact: "Michael Jones — Spouse · (555) 010-2002",
      createdAt: dt(-120),
    },
  ];

  const documents = [
    {
      id: "doc_001",
      name: "Employment Agreement",
      type: "PDF · Signed",
      date: "2021-03-03",
      createdAt: dt(-120),
    },
    {
      id: "doc_002",
      name: "Role & Responsibilities",
      type: "PDF",
      date: "2024-01-12",
      createdAt: dt(-119),
    },
    {
      id: "doc_003",
      name: "Org Chart — Compliance",
      type: "PDF",
      date: "2026-04-02",
      createdAt: dt(-118),
    },
    {
      id: "doc_004",
      name: "Code of Conduct Acknowledgement",
      type: "PDF · Signed",
      date: "2026-01-08",
      createdAt: dt(-117),
    },
  ];

  return {
    agencies,
    matters,
    communications,
    deficiencies,
    escalations,
    knowledge,
    sops,
    tasks,
    alerts,
    bonusOpportunities,
    compensation,
    reviewTargets,
    employeeProfile,
    documents,
  };
}
